name: Github CI build

# GITHUB_REF_NAME in the form of release-$VERSION-$RELEASE-$EXTRA_NAME

on:
  push:
    tags:
      - release-**-**-**
  workflow_dispatch:

env:
  RELEASESDK: 4.5.0.16

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Build mic
      run: docker run --rm --privileged -v $PWD:/share --env-file env.list -e VERSION -e RELEASE -e EXTRA_NAME coderus/sailfishos-platform-sdk:$RELEASESDK /bin/bash -c " 
            ./scripts/create-image.sh --release $RELEASE --version $VERSION*

    - name: Update release
      run: |
        gh release upload ${{ github.ref_name }} output/mic/sfe-*/*.zip --clobber 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
